name = "SeisNoise"
uuid = "8cc7c3c0-6b5d-11e9-39fe-c9cd0236e08b"
authors = ["timclements <thclements@g.harvard.edu>"]
version = "0.5.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SeisIO = "b372bb87-02dd-52bb-bcf6-c30dd83fd342"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Adapt = "1.0.1, 2.0, 3.0"
DSP = "0.6"
FFTW = "1.1"
GPUArrays = "3.1, 4.0, 5.0, 6.2"
Glob = "1.2"
JLD2 = "0.1, 0.2"
RecipesBase = "1.1"
SeisIO = "1.0"
StatsBase = "0.32,0.33"
julia = "1"
